"""Modified books table to accept nullable inputs

Revision ID: d9cd87aacf84
Revises: 1b989058b24c
Create Date: 2026-07-14 10:14:09.588617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9cd87aacf84'
down_revision: Union[str, Sequence[str], None] = '1b989058b24c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'publisher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'publication_year',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('books', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('books', 'publication_year',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('books', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books', 'publisher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
